// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DapperPerfTest.EFCore6.Scaffold
{
    public partial class NorthwindContextModel
    {
        partial void Initialize()
        {
            var customerCustomerDemo = CustomerCustomerDemoEntityType.Create(this);
            var dbResultint = DbResultintEntityType.Create(this);
            var alphabeticalListOfProduct = AlphabeticalListOfProductEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var categorySalesFor1997 = CategorySalesFor1997EntityType.Create(this);
            var currentProductList = CurrentProductListEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var customerAndSuppliersByCity = CustomerAndSuppliersByCityEntityType.Create(this);
            var customerDemographic = CustomerDemographicEntityType.Create(this);
            var employee = EmployeeEntityType.Create(this);
            var invoice = InvoiceEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderDetail = OrderDetailEntityType.Create(this);
            var orderDetailsExtended = OrderDetailsExtendedEntityType.Create(this);
            var ordersQry = OrdersQryEntityType.Create(this);
            var orderSubtotal = OrderSubtotalEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productsAboveAveragePrice = ProductsAboveAveragePriceEntityType.Create(this);
            var productSalesFor1997 = ProductSalesFor1997EntityType.Create(this);
            var productsByCategory = ProductsByCategoryEntityType.Create(this);
            var quarterlyOrder = QuarterlyOrderEntityType.Create(this);
            var region = RegionEntityType.Create(this);
            var salesByCategory = SalesByCategoryEntityType.Create(this);
            var salesTotalsByAmount = SalesTotalsByAmountEntityType.Create(this);
            var shipper = ShipperEntityType.Create(this);
            var summaryOfSalesByQuarter = SummaryOfSalesByQuarterEntityType.Create(this);
            var summaryOfSalesByYear = SummaryOfSalesByYearEntityType.Create(this);
            var supplier = SupplierEntityType.Create(this);
            var territory = TerritoryEntityType.Create(this);
            var employeeTerritory = EmployeeTerritoryEntityType.Create(this);

            CustomerCustomerDemoEntityType.CreateForeignKey1(customerCustomerDemo, customer);
            CustomerCustomerDemoEntityType.CreateForeignKey2(customerCustomerDemo, customerDemographic);
            EmployeeEntityType.CreateForeignKey1(employee, employee);
            OrderEntityType.CreateForeignKey1(order, customer);
            OrderEntityType.CreateForeignKey2(order, employee);
            OrderEntityType.CreateForeignKey3(order, shipper);
            OrderDetailEntityType.CreateForeignKey1(orderDetail, order);
            OrderDetailEntityType.CreateForeignKey2(orderDetail, product);
            ProductEntityType.CreateForeignKey1(product, category);
            ProductEntityType.CreateForeignKey2(product, supplier);
            TerritoryEntityType.CreateForeignKey1(territory, region);
            EmployeeTerritoryEntityType.CreateForeignKey1(employeeTerritory, employee);
            EmployeeTerritoryEntityType.CreateForeignKey2(employeeTerritory, territory);

            CustomerEntityType.CreateSkipNavigation1(customer, customerDemographic, customerCustomerDemo);
            CustomerDemographicEntityType.CreateSkipNavigation1(customerDemographic, customer, customerCustomerDemo);
            EmployeeEntityType.CreateSkipNavigation1(employee, territory, employeeTerritory);
            TerritoryEntityType.CreateSkipNavigation1(territory, employee, employeeTerritory);

            CustomerCustomerDemoEntityType.CreateAnnotations(customerCustomerDemo);
            DbResultintEntityType.CreateAnnotations(dbResultint);
            AlphabeticalListOfProductEntityType.CreateAnnotations(alphabeticalListOfProduct);
            CategoryEntityType.CreateAnnotations(category);
            CategorySalesFor1997EntityType.CreateAnnotations(categorySalesFor1997);
            CurrentProductListEntityType.CreateAnnotations(currentProductList);
            CustomerEntityType.CreateAnnotations(customer);
            CustomerAndSuppliersByCityEntityType.CreateAnnotations(customerAndSuppliersByCity);
            CustomerDemographicEntityType.CreateAnnotations(customerDemographic);
            EmployeeEntityType.CreateAnnotations(employee);
            InvoiceEntityType.CreateAnnotations(invoice);
            OrderEntityType.CreateAnnotations(order);
            OrderDetailEntityType.CreateAnnotations(orderDetail);
            OrderDetailsExtendedEntityType.CreateAnnotations(orderDetailsExtended);
            OrdersQryEntityType.CreateAnnotations(ordersQry);
            OrderSubtotalEntityType.CreateAnnotations(orderSubtotal);
            ProductEntityType.CreateAnnotations(product);
            ProductsAboveAveragePriceEntityType.CreateAnnotations(productsAboveAveragePrice);
            ProductSalesFor1997EntityType.CreateAnnotations(productSalesFor1997);
            ProductsByCategoryEntityType.CreateAnnotations(productsByCategory);
            QuarterlyOrderEntityType.CreateAnnotations(quarterlyOrder);
            RegionEntityType.CreateAnnotations(region);
            SalesByCategoryEntityType.CreateAnnotations(salesByCategory);
            SalesTotalsByAmountEntityType.CreateAnnotations(salesTotalsByAmount);
            ShipperEntityType.CreateAnnotations(shipper);
            SummaryOfSalesByQuarterEntityType.CreateAnnotations(summaryOfSalesByQuarter);
            SummaryOfSalesByYearEntityType.CreateAnnotations(summaryOfSalesByYear);
            SupplierEntityType.CreateAnnotations(supplier);
            TerritoryEntityType.CreateAnnotations(territory);
            EmployeeTerritoryEntityType.CreateAnnotations(employeeTerritory);

            AddAnnotation("ProductVersion", "6.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
