// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DapperPerfTest.EFCore6.Scaffold
{
    [DbContext(typeof(NorthwindContext))]
    public partial class NorthwindContextModel : RuntimeModel
    {
        static NorthwindContextModel()
        {
            var model = new NorthwindContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static NorthwindContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
